name: Workflow名称
run-name: 运行实例名称

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ vars.VARIABLE_TEST }}